version: "3"
services:
  worker:
    build: .
    image: template
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
  web:
    build: .
    image: template
    volumes:
      - .:/app
    ports:
      - "3500:3500"
    depends_on:
      - worker
  postgres:
    image: postgres:11 # FYI: https://devcenter.heroku.com/ja/articles/heroku-postgresql#version-support
    ports:
      - "5432:5432"
  redis:
    image: redis:6 # FYI: https://devcenter.heroku.com/articles/heroku-redis#version-support-and-legacy-infrastructure
    ports:
      - "6379:6379"
